CREATE OR REPLACE FUNCTION insert_country(geo_code varchar, name varchar, abbreviation varchar)
RETURNS void AS $$
DECLARE
    new_geo_id integer;
BEGIN
    -- Insert into geographic_boundary
    INSERT INTO public.geographic_boundary (geo_code, name, abbreviation, type_id)
    VALUES (geo_code, name, abbreviation, 1)
    RETURNING geo_id INTO new_geo_id;

    -- Insert into country
    INSERT INTO public.country (geo_id)
    VALUES (new_geo_id);
END;
$$ LANGUAGE plpgsql;

-- Example usage
-- SELECT insert_country('TH', 'Thailand', 'TH');
-- SELECT insert_country('US', 'United States', 'US');

-- select insert_country('TH', 'Thailand', 'TH');


select insert_country('AF', 'Afghanistan', 'AF');
select insert_country('AL', 'Albania', 'AL');
select insert_country('DZ', 'Algeria', 'DZ');
select insert_country('AS', 'American Samoa', 'AS');
select insert_country('AD', 'Andorra', 'AD');
select insert_country('AO', 'Angola', 'AO');
select insert_country('AI', 'Anguilla', 'AI');
select insert_country('AQ', 'Antarctica', 'AQ');
select insert_country('AG', 'Antigua and Barbuda', 'AG');
select insert_country('AR', 'Argentina', 'AR');
select insert_country('AM', 'Armenia', 'AM');
select insert_country('AW', 'Aruba', 'AW');
select insert_country('AU', 'Australia', 'AU');
select insert_country('AT', 'Austria', 'AT');
select insert_country('AZ', 'Azerbaijan', 'AZ');
select insert_country('BS', 'Bahamas', 'BS');
select insert_country('BH', 'Bahrain', 'BH');
select insert_country('BD', 'Bangladesh', 'BD');
select insert_country('BB', 'Barbados', 'BB');
select insert_country('BY', 'Belarus', 'BY');
select insert_country('BE', 'Belgium', 'BE');
select insert_country('BZ', 'Belize', 'BZ');
select insert_country('BJ', 'Benin', 'BJ');
select insert_country('BM', 'Bermuda', 'BM');
select insert_country('BT', 'Bhutan', 'BT');
select insert_country('BO', 'Bolivia, Plurinational State of', 'BO');
select insert_country('BQ', 'Bonaire, Sint Eustatius and Saba', 'BQ');
select insert_country('BA', 'Bosnia and Herzegovina', 'BA');
select insert_country('BW', 'Botswana', 'BW');
select insert_country('BV', 'Bouvet Island', 'BV');
select insert_country('BR', 'Brazil', 'BR');
select insert_country('IO', 'British Indian Ocean Territory', 'IO');
select insert_country('BN', 'Brunei Darussalam', 'BN');
select insert_country('BG', 'Bulgaria', 'BG');
select insert_country('BF', 'Burkina Faso', 'BF');
select insert_country('BI', 'Burundi', 'BI');
select insert_country('KH', 'Cambodia', 'KH');
select insert_country('CM', 'Cameroon', 'CM');
select insert_country('CA', 'Canada', 'CA');
select insert_country('CV', 'Cape Verde', 'CV');
select insert_country('KY', 'Cayman Islands', 'KY');
select insert_country('CF', 'Central African Republic', 'CF');
select insert_country('TD', 'Chad', 'TD');
select insert_country('CL', 'Chile', 'CL');
select insert_country('CN', 'China', 'CN');
select insert_country('CX', 'Christmas Island', 'CX');
select insert_country('CC', 'Cocos (Keeling) Islands', 'CC');
select insert_country('CO', 'Colombia', 'CO');
select insert_country('KM', 'Comoros', 'KM');
select insert_country('CG', 'Congo', 'CG');
select insert_country('CD', 'Congo, the Democratic Republic of the', 'CD');
select insert_country('CK', 'Cook Islands', 'CK');
select insert_country('CR', 'Costa Rica', 'CR');
select insert_country('HR', 'Croatia', 'HR');
select insert_country('CU', 'Cuba', 'CU');
select insert_country('CW', 'Curaçao', 'CW');
select insert_country('CY', 'Cyprus', 'CY');
select insert_country('CZ', 'Czech Republic', 'CZ');
select insert_country('CI', 'Côte dIvoire', 'CI');
select insert_country('DK', 'Denmark', 'DK');
select insert_country('DJ', 'Djibouti', 'DJ');
select insert_country('DM', 'Dominica', 'DM');
select insert_country('DO', 'Dominican Republic', 'DO');
select insert_country('EC', 'Ecuador', 'EC');
select insert_country('EG', 'Egypt', 'EG');
select insert_country('SV', 'El Salvador', 'SV');
select insert_country('GQ', 'Equatorial Guinea', 'GQ');
select insert_country('ER', 'Eritrea', 'ER');
select insert_country('EE', 'Estonia', 'EE');
select insert_country('SZ', 'Eswatini', 'SZ');
select insert_country('ET', 'Ethiopia', 'ET');
select insert_country('FK', 'Falkland Islands (Malvinas)', 'FK');
select insert_country('FO', 'Faroe Islands', 'FO');
select insert_country('FJ', 'Fiji', 'FJ');
select insert_country('FI', 'Finland', 'FI');
select insert_country('FR', 'France', 'FR');
select insert_country('GF', 'French Guiana', 'GF');
select insert_country('PF', 'French Polynesia', 'PF');
select insert_country('TF', 'French Southern Territories', 'TF');
select insert_country('GA', 'Gabon', 'GA');
select insert_country('GM', 'Gambia', 'GM');
select insert_country('GE', 'Georgia', 'GE');
select insert_country('DE', 'Germany', 'DE');
select insert_country('GH', 'Ghana', 'GH');
select insert_country('GI', 'Gibraltar', 'GI');
select insert_country('GR', 'Greece', 'GR');
select insert_country('GL', 'Greenland', 'GL');
select insert_country('GD', 'Grenada', 'GD');
select insert_country('GP', 'Guadeloupe', 'GP');
select insert_country('GU', 'Guam', 'GU');
select insert_country('GT', 'Guatemala', 'GT');
select insert_country('GG', 'Guernsey', 'GG');
select insert_country('GN', 'Guinea', 'GN');
select insert_country('GW', 'Guinea-Bissau', 'GW');
select insert_country('GY', 'Guyana', 'GY');
select insert_country('HT', 'Haiti', 'HT');
select insert_country('HM', 'Heard Island and McDonald Islands', 'HM');
select insert_country('VA', 'Holy See (Vatican City State)', 'VA');
select insert_country('HN', 'Honduras', 'HN');
select insert_country('HK', 'Hong Kong', 'HK');
select insert_country('HU', 'Hungary', 'HU');
select insert_country('IS', 'Iceland', 'IS');
select insert_country('IN', 'India', 'IN');
select insert_country('ID', 'Indonesia', 'ID');
select insert_country('IR', 'Iran, Islamic Republic of', 'IR');
select insert_country('IQ', 'Iraq', 'IQ');
select insert_country('IE', 'Ireland', 'IE');
select insert_country('IM', 'Isle of Man', 'IM');
select insert_country('IL', 'Israel', 'IL');
select insert_country('IT', 'Italy', 'IT');
select insert_country('JM', 'Jamaica', 'JM');
select insert_country('JP', 'Japan', 'JP');
select insert_country('JE', 'Jersey', 'JE');
select insert_country('JO', 'Jordan', 'JO');
select insert_country('KZ', 'Kazakhstan', 'KZ');
select insert_country('KE', 'Kenya', 'KE');
select insert_country('KI', 'Kiribati', 'KI');
select insert_country('KP', 'Korea, Democratic Peoples Republic of', 'KP');
select insert_country('KR', 'Korea, Republic of', 'KR');
select insert_country('KW', 'Kuwait', 'KW');
select insert_country('KG', 'Kyrgyzstan', 'KG');
select insert_country('LA', 'Lao Peoples Democratic Republic', 'LA');
select insert_country('LV', 'Latvia', 'LV');
select insert_country('LB', 'Lebanon', 'LB');
select insert_country('LS', 'Lesotho', 'LS');
select insert_country('LR', 'Liberia', 'LR');
select insert_country('LY', 'Libya', 'LY');
select insert_country('LI', 'Liechtenstein', 'LI');
select insert_country('LT', 'Lithuania', 'LT');
select insert_country('LU', 'Luxembourg', 'LU');
select insert_country('MO', 'Macao', 'MO');
select insert_country('MK', 'Macedonia, the Former Yugoslav Republic of', 'MK');
select insert_country('MG', 'Madagascar', 'MG');
select insert_country('MW', 'Malawi', 'MW');
select insert_country('MY', 'Malaysia', 'MY');
select insert_country('MV', 'Maldives', 'MV');
select insert_country('ML', 'Mali', 'ML');
select insert_country('MT', 'Malta', 'MT');
select insert_country('MH', 'Marshall Islands', 'MH');
select insert_country('MQ', 'Martinique', 'MQ');
select insert_country('MR', 'Mauritania', 'MR');
select insert_country('MU', 'Mauritius', 'MU');
select insert_country('YT', 'Mayotte', 'YT');
select insert_country('MX', 'Mexico', 'MX');
select insert_country('FM', 'Micronesia, Federated States of', 'FM');
select insert_country('MD', 'Moldova, Republic of', 'MD');
select insert_country('MC', 'Monaco', 'MC');
select insert_country('MN', 'Mongolia', 'MN');
select insert_country('ME', 'Montenegro', 'ME');
select insert_country('MS', 'Montserrat', 'MS');
select insert_country('MA', 'Morocco', 'MA');
select insert_country('MZ', 'Mozambique', 'MZ');
select insert_country('MM', 'Myanmar', 'MM');
select insert_country('NA', 'Namibia', 'NA');
select insert_country('NR', 'Nauru', 'NR');
select insert_country('NP', 'Nepal', 'NP');
select insert_country('NL', 'Netherlands', 'NL');
select insert_country('NC', 'New Caledonia', 'NC');
select insert_country('NZ', 'New Zealand', 'NZ');
select insert_country('NI', 'Nicaragua', 'NI');
select insert_country('NE', 'Niger', 'NE');
select insert_country('NG', 'Nigeria', 'NG');
select insert_country('NU', 'Niue', 'NU');
select insert_country('NF', 'Norfolk Island', 'NF');
select insert_country('MP', 'Northern Mariana Islands', 'MP');
select insert_country('NO', 'Norway', 'NO');
select insert_country('OM', 'Oman', 'OM');
select insert_country('PK', 'Pakistan', 'PK');
select insert_country('PW', 'Palau', 'PW');
select insert_country('PS', 'Palestine, State of', 'PS');
select insert_country('PA', 'Panama', 'PA');
select insert_country('PG', 'Papua New Guinea', 'PG');
select insert_country('PY', 'Paraguay', 'PY');
select insert_country('PE', 'Peru', 'PE');
select insert_country('PH', 'Philippines', 'PH');
select insert_country('PN', 'Pitcairn', 'PN');
select insert_country('PL', 'Poland', 'PL');
select insert_country('PT', 'Portugal', 'PT');
select insert_country('PR', 'Puerto Rico', 'PR');
select insert_country('QA', 'Qatar', 'QA');
select insert_country('RO', 'Romania', 'RO');
select insert_country('RU', 'Russian Federation', 'RU');
select insert_country('RW', 'Rwanda', 'RW');
select insert_country('RE', 'Réunion', 'RE');
select insert_country('BL', 'Saint Barthélemy', 'BL');
select insert_country('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'SH');
select insert_country('KN', 'Saint Kitts and Nevis', 'KN');
select insert_country('LC', 'Saint Lucia', 'LC');
select insert_country('MF', 'Saint Martin (French part)', 'MF');
select insert_country('PM', 'Saint Pierre and Miquelon', 'PM');
select insert_country('VC', 'Saint Vincent and the Grenadines', 'VC');
select insert_country('WS', 'Samoa', 'WS');
select insert_country('SM', 'San Marino', 'SM');
select insert_country('ST', 'Sao Tome and Principe', 'ST');
select insert_country('SA', 'Saudi Arabia', 'SA');
select insert_country('SN', 'Senegal', 'SN');
select insert_country('RS', 'Serbia', 'RS');
select insert_country('SC', 'Seychelles', 'SC');
select insert_country('SL', 'Sierra Leone', 'SL');
select insert_country('SG', 'Singapore', 'SG');
select insert_country('SX', 'Sint Maarten (Dutch part)', 'SX');
select insert_country('SK', 'Slovakia', 'SK');
select insert_country('SI', 'Slovenia', 'SI');
select insert_country('SB', 'Solomon Islands', 'SB');
select insert_country('SO', 'Somalia', 'SO');
select insert_country('ZA', 'South Africa', 'ZA');
select insert_country('GS', 'South Georgia and the South Sandwich Islands', 'GS');
select insert_country('SS', 'South Sudan', 'SS');
select insert_country('ES', 'Spain', 'ES');
select insert_country('LK', 'Sri Lanka', 'LK');
select insert_country('SD', 'Sudan', 'SD');
select insert_country('SR', 'Suriname', 'SR');
select insert_country('SJ', 'Svalbard and Jan Mayen', 'SJ');
select insert_country('SE', 'Sweden', 'SE');
select insert_country('CH', 'Switzerland', 'CH');
select insert_country('SY', 'Syrian Arab Republic', 'SY');
select insert_country('TW', 'Taiwan, Province of China', 'TW');
select insert_country('TJ', 'Tajikistan', 'TJ');
select insert_country('TZ', 'Tanzania, United Republic of', 'TZ');
-- select insert_country('TH', 'Thailand', 'TH');
-- เอา thai ออก เพราะว่ามีใน database อยู่เเล้ว
select insert_country('TL', 'Timor-Leste', 'TL');
select insert_country('TG', 'Togo', 'TG');
select insert_country('TK', 'Tokelau', 'TK');
select insert_country('TO', 'Tonga', 'TO');
select insert_country('TT', 'Trinidad and Tobago', 'TT');
select insert_country('TN', 'Tunisia', 'TN');
select insert_country('TR', 'Turkey', 'TR');
select insert_country('TM', 'Turkmenistan', 'TM');
select insert_country('TC', 'Turks and Caicos Islands', 'TC');
select insert_country('TV', 'Tuvalu', 'TV');
select insert_country('UG', 'Uganda', 'UG');
select insert_country('UA', 'Ukraine', 'UA');
select insert_country('AE', 'United Arab Emirates', 'AE');
select insert_country('GB', 'United Kingdom', 'GB');
select insert_country('US', 'United States', 'US');
select insert_country('UM', 'United States Minor Outlying Islands', 'UM');
select insert_country('UY', 'Uruguay', 'UY');
select insert_country('UZ', 'Uzbekistan', 'UZ');
select insert_country('VU', 'Vanuatu', 'VU');
select insert_country('VE', 'Venezuela, Bolivarian Republic of', 'VE');
select insert_country('VN', 'Viet Nam', 'VN');
select insert_country('VG', 'Virgin Islands, British', 'VG');
select insert_country('VI', 'Virgin Islands, U.S.', 'VI');
select insert_country('WF', 'Wallis and Futuna', 'WF');
select insert_country('EH', 'Western Sahara', 'EH');
select insert_country('YE', 'Yemen', 'YE');
select insert_country('ZM', 'Zambia', 'ZM');
select insert_country('ZW', 'Zimbabwe', 'ZW');
select insert_country('AX', 'Åland Islands', 'AX');